version: 2
updates:
- directory: '/'
  open-pull-requests-limit: 5
  package-ecosystem: docker
  schedule:
    interval: daily
      
- directory: '/'
  open-pull-requests-limit: 5
  package-ecosystem: nuget
  schedule:
    interval: daily
