name: Docker Publish
on:
  push:
    branches: [main]
    tags: [v*]
    paths:
    - "src/Safir.Manager/**"
env:
  IMAGE_NAME: safir-manager
jobs:
  docker_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build . --file Dockerfile  \
          --build-arg GithubUsername=${{ github.actor }} \
          --build-arg GithubPassword=${{ secrets.GITHUB_TOKEN }} \
          --tag $IMAGE_NAME

    - name: Log into registries
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u unstoppablemango --password-stdin
        
    - name: Push image
      run: |
        GITHUB_IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
        DOCKERHUB_IMAGE_ID=unstoppablemango/$IMAGE_NAME

        # Change all uppercase to lowercase
        GITHUB_IMAGE_ID=$(echo $GITHUB_IMAGE_ID | tr '[A-Z]' '[a-z]')
        DOCKERHUB_IMAGE_ID=$(echo $DOCKERHUB_IMAGE_ID | tr '[A-Z]' '[a-z]')
        
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest

        echo GITHUB_IMAGE_ID=$GITHUB_IMAGE_ID
        echo DOCKERHUB_IMAGE_ID=$DOCKERHUB_IMAGE_ID
        echo VERSION=$VERSION

        docker tag $IMAGE_NAME $GITHUB_IMAGE_ID:$VERSION
        docker tag $IMAGE_NAME $DOCKERHUB_IMAGE_ID:$VERSION
        
        docker push $GITHUB_IMAGE_ID:$VERSION
        docker push $DOCKERHUB_IMAGE_ID:$VERSION
