name: NuGet Publish
on:
  push:
    branches: [main]
    tags: ["*.*.*"]
    paths:
    - "Directory.build.*"
    - "src/*.Client/**"
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  CI: true
jobs:
  package_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Build solution
      run: dotnet build --configuration Release --nologo
      env:
        GithubUsername: ${{ github.actor }}
        GithubPassword: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: dotnet test --configuration Release --no-build --nologo
    - name: Package libraries
      run: dotnet pack --configuration Release --no-build --nologo
    - name: Push packages to Github
      run: |
        dotnet nuget push src/**/*.nupkg \
          --source https://nuget.pkg.github.com/unmango/index.json \
          --api-key ${{ secrets.GITHUB_TOKEN }}
